### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by samyukthasudhakar**
As part of this PR I've created the landing page for the component library. 
Do let me know if any changes are required 😄

Live : https://breezeui.netlify.app/

### CODE REVIEW

**Review by vrx29 — APPROVED** [review]

**Review by partha8 — APPROVED** [review]
LGTM, great work @samyukthasudhakar!

**Comment by RakshaPawar108** [comment]
Such a beautiful and minimalistic landing page Samyuktha! Loved it

**Review by RakshaPawar108 — APPROVED** [review]

**Comment by foolhardy21** [comment]
nice UI.

**Review by ParthParolekar — APPROVED** [review]
This looks really clean. Nice work!

**Review by vrinda-mahajan — APPROVED** [review]
Awesome UI.👍

**Comment by samyukthasudhakar** [comment]
> LGTM, great work @samyukthasudhakar!

Thank you @partha8  :D

**Comment by samyukthasudhakar** [comment]
> Such a beautiful and minimalistic landing page Samyuktha! Loved it

Thank you so much Raksha, glad you loved it ☺

**Comment by samyukthasudhakar** [comment]
> nice UI.

Thanks !

**Comment by samyukthasudhakar** [comment]
> This looks really clean. Nice work!

Thank you !!

**Comment by samyukthasudhakar** [comment]
> Awesome UI.👍

Thanks @vrinda-mahajan 😄

**Pull request merged**
