### PR TITLE
Badge and button components.

### PR DESCRIPTION
**Pull request by samyukthasudhakar**
As part of this PR I've created the following :

- Badge component
- Button Compoent

Live : https://badge-and-button.netlify.app/docs.html

Do let me know if the changes look alright and if anything could be done better.

### CODE REVIEW

**Review by hsnice16 — CHANGES_REQUESTED** [review]
In the UI, 
image
Give atleast a line space before next starting div. It will look good.

**Comment by aayushjain-code** [comment]
Clean UI try to make it more to center

**Review by Maianki — APPROVED** [review]
Everything looks good. You can merge it.

**Comment by samyukthasudhakar** [comment]
> Everything looks good. You can merge it.

Thank you 😄

**Comment by samyukthasudhakar** [comment]
> Clean UI try to make it more to center

Sure will do, thanks 👍🏽

**Comment by samyukthasudhakar** [comment]
> In the UI, image Give atleast a line space before next starting div. It will look good.

Have made the changes as suggested. Thank you !

**Pull request merged**
